# Site settings
title: "Repeat Until Keypressed"
bye_message: "Î»"
baseurl: "/"
url: "http://marco-lopes.com"
description: "Sharing technical and delivery knowledge"

title_image: "/assets/images/ruk-header.jpg"

include: [ _pages ]
pagesdir: _pages
destination: _site

exclude: ["Gemfile*", "README.*", "Rakefile"]

disqus: ruk

# Header settings
author: "Marco Lopes"
social:
    github: "mlopes"
    twitter: "mpmlopes"
    fingerprint_key: "14D4 0CA1 E1A8 06A0 15C4  A06B 372E C33E B388 121A"

google:
    analytics: "UA-106464365-1"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

gems:
  - jekyll-feed
  - amp-jekyll

ampdir: amp
